# Generated by Django 5.0.1 on 2024-02-19 15:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Book",
        ),
    ]
