# Generated by Django 5.0 on 2023-12-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_app", "0002_alter_profile_options_profile_exp_alter_profile_iin"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={
                "ordering": ("-exp", "-name"),
                "verbose_name": "Профиль",
                "verbose_name_plural": "Профили",
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Имя"
            ),
        ),
    ]
