# Generated by Django 5.0 on 2023-12-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_app", "0003_alter_profile_options_profile_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={
                "ordering": ("is_active", "-name"),
                "verbose_name": "Профиль",
                "verbose_name_plural": "Профили",
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен ли профиль"),
        ),
    ]
