# Generated by Django 5.0 on 2023-12-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_app", "0004_alter_profile_options_profile_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vacansie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=300,
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Описание"),
                ),
                (
                    "salary",
                    models.PositiveIntegerField(
                        blank=True, default=0, verbose_name="Зарплата"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Активность вакансии"
                    ),
                ),
            ],
            options={
                "verbose_name": "Вакансия",
                "verbose_name_plural": "Вакансии",
                "ordering": ("is_active", "-salary", "-title"),
            },
        ),
    ]
