# Generated by Django 5.0 on 2024-01-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_app", "0005_vip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vip",
            name="priority",
            field=models.IntegerField(
                blank=True, db_index=True, default=5, verbose_name="Приоритет"
            ),
        ),
    ]
