# Generated by Django 5.0 on 2024-01-08 15:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_app", "0006_alter_vip_priority"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True, default="", verbose_name="Текст комментария"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=django.utils.timezone.now,
                        max_length=300,
                        verbose_name="дата и время создания",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активеность"),
                ),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        default="",
                        max_length=100,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_app.item",
                        verbose_name="Объявление",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        default="",
                        max_length=100,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
                "ordering": ("-created",),
            },
        ),
    ]
