# Generated by Django 5.0 on 2024-01-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_app", "0008_tagitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                db_index=True,
                default="",
                max_length=100,
                to="django_app.tagitem",
                verbose_name="Тэги",
            ),
        ),
    ]
