# Generated by Django 5.0 on 2024-01-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_app", "0011_itembug"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="item/avatars",
                verbose_name="Аватарка",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="file",
            field=models.FileField(
                blank=True,
                default=None,
                null=True,
                upload_to="item/files",
                verbose_name="Инструкция",
            ),
        ),
    ]
