# Generated by Django 5.0 on 2024-01-15 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_app", "0012_item_avatar_item_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="item/avatars",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "png", "jpeg", "bmp"]
                    )
                ],
                verbose_name="Аватарка",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="file",
            field=models.FileField(
                blank=True,
                default=None,
                null=True,
                upload_to="item/files",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["xlsx", "docx", "pdf"]
                    )
                ],
                verbose_name="Инструкция",
            ),
        ),
    ]
