# Generated by Django 5.0 on 2024-01-19 13:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_app", "0017_alter_item_options_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
