# Generated by Django 5.0 on 2024-01-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_app", "0018_delete_profile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={
                "ordering": ("-is_moderate", "is_active", "title"),
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.AddField(
            model_name="item",
            name="is_moderate",
            field=models.BooleanField(
                default=False, verbose_name="Проверено ли объявление модератором?"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="is_active",
            field=models.BooleanField(
                default=True, verbose_name="Активность объявления"
            ),
        ),
    ]
