# Generated by Django 5.0.2 on 2024-02-23 13:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("django_app", "0002_delete_book"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=300,
                        verbose_name="Book title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Book description"
                    ),
                ),
                (
                    "book_file",
                    models.FileField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to="books",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "docx", "FB2"]
                            )
                        ],
                        verbose_name="Book file",
                    ),
                ),
            ],
        ),
    ]
